---
- name: Install HTTPD servers
  hosts: n1
  become: yes
  tasks:
    - name: Install HTTPD
      yum:
        name: httpd
        state: present

    - name: start httpd
      service:
        name: httpd
        state: started

    - name: enable httpd
      service:
       name: httpd
       enabled: yes
...
