---
- name: variable testing
  hosts: g3
  become: yes
  vars:
    myusername: Preye

  tasks:
   - name: updating page
     template:
       src: steady.html
       dest: /var/www/html/steady3.html
...

