---
- name: deploy web App
  hosts: n1
  become: yes

  tasks:
    - name: Install git
      yum:
        name: git
        state: present

    - name: Host code
      git:
        repo: https://github.com/Tracyerite/ecomm-3.git
        dest:/var/www/html

...
