# ansible n1 -m file -a "path/home/ec2-user/ all_dir state=directory"
---
- name: update n1 severs
  hosts: n1
  become: yes
  tasks:
    - name: create directory
      file:
        path: /home/ec2-user/new-dir
        state: directory 
...
