---
- name: variable testing
  hosts: g3
  become: yes
  vars:
    myusername: Tracy

  tasks:
   - name: updating page
     template:
       src: steady.html
       dest: /var/www/html/steady.html
...
